### ISSUE TITLE
Damm Looking !!!

### ISSUE THREAD

**Issue by garg-madhur-garg** [garg-madhur-garg/GitHub_Profile_Viewer#2]
**Can anyone help me to make a better UI for this Utility**

**Comment by ndmtuan** [comment]
i can work on the issue, pls sent me now!!!!!! thanks you so much

**Comment by LieuMai** [comment]
I believe I can improve this UI. Can you assign this for me?

**Comment by garg-madhur-garg** [comment]
Are you both the same guy 🤔 ?
@LieuMai
@ndmtuan

**Comment by LieuMai** [comment]
> Are you both the same guy 🤔 ? @LieuMai @ndmtuan

Haha, no sir, but we have same teacher I guess. We are studying how to contribute a opensource project. So this is our practice exercise.

I will be preciate if you can give us a try!!! ^_^

**Comment by garg-madhur-garg** [comment]
Issue assigned @LieuMai

**Comment by garg-madhur-garg** [comment]
You both can give it a try
@LieuMai 
@ndmtuan 

Best of Luck 👍

**Comment by LieuMai** [comment]
Would you like to style the red part too?  I found that demo can fetch data into the screen, but in source code I notice that I can't fetch data. 

![Ảnh chụp màn hình 2021-11-10 155241](https://user-images.githubusercontent.com/56626332/141081243-2dafe18c-bd0d-4b63-bc6d-01f3015b4d63.png)

**Comment by garg-madhur-garg** [comment]
**Would you like to style the red part too?** ---> YES.
**I found that demo can fetch data into the screen, but in source code I notice that I can't fetch data. --->**

**Step 1**: Make a file with name _`.env`_ in root folder (where _`.gitignore`_ is present).
**Step 2:** Copy and Paste  _`REACT_APP_GITHUB_API = "https://api.github.com/users/"`_ in _`.env`_ file and save it.
**Step 3:** Do `npm start` again.

@LieuMai

**Comment by garg-madhur-garg** [comment]
Let me know it worked or not !!

@LieuMai

**Comment by LieuMai** [comment]
> Let me know it worked or not !!
> 
> @LieuMai

It worked. Thank you, sir!

**Comment by LieuMai** [comment]
@garg-madhur-garg  I created a pull request. Please check and review if you like it or not. I will improve it.

**Comment by garg-madhur-garg** [comment]
>If you want then you can make this page responsive.
>And I think instead of splitting you can Capitalize the letters😊
>And any other suggestions are always welcome !!

I am merging your PR, 
You can continue your work on above mention points 👍

@LieuMai

**Comment by garg-madhur-garg** [comment]
Are you working on this ??
@LieuMai

**Comment by LieuMai** [comment]
@garg-madhur-garg The new design is done but it isn't responsive. I will create a pull request if you need it now. I'm so sorry but I couldn't comeback in the next two weeks. You can assign this issue for other people. When I completed the responsive part, I will create a pull request.

**Comment by garg-madhur-garg** [comment]
ok, you can create a pull request whenever your work is done
@LieuMai
